ALTER TABLE FREIGHT_UPDATE_DETAIL ADD effective_date DATE NULL;
ALTER TABLE FREIGHT_UPDATE_DETAIL DROP PRIMARY KEY;
ALTER TABLE FREIGHT_UPDATE_DETAIL ADD PRIMARY KEY (uuid, effective_date);

ALTER TABLE SUPPLIER_INFO ADD business_center VARCHAR(128) NULL;
ALTER TABLE SUPPLIER_INFO ADD corp_billed VARCHAR(1) NULL;
ALTER TABLE SUPPLIER_INFO ADD true_fob_supplier VARCHAR(1) NULL;